version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_PASSWORD: P4ssw0rd
      MYSQL_DATABASE: fastapi_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  api:
    depends_on:
      db:
        condition: service_healthy
    image: sarthak5784/fastapi-simple-server
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_PASSWORD: P4ssw0rd
      MYSQL_DATABASE: fastapi_app
      MYSQL_HOST: db