apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/name: caddy-ingress-controller
  name: caddy-metrics
  namespace: caddy-system
spec:
  ports:
  - name: metrics
    port: 9765
    protocol: TCP
    targetPort: 9765
  selector:
    app.kubernetes.io/instance: mycaddy
    app.kubernetes.io/name: caddy-ingress-controller
  type: ClusterIP