apiVersion: v1
data:
  .my.cnf: |
    [client]
    host=mysql
    port=3306
    user=root
    password=P@ssw0rd
kind: ConfigMap
metadata:
  name: mysql-exporter-cnf
  namespace: testing
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: testing
  labels:
    app: mysqld-exporter
spec:
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  selector:
    app: mysqld-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.15.0
          args:
            - "--config.my-cnf=/etc/mysql/.my.cnf"
          ports:
            - name: metrics
              containerPort: 9104
          volumeMounts:
            - name: cnf-volume
              mountPath: /etc/mysql/.my.cnf
              subPath: .my.cnf
      volumes:
        - name: cnf-volume
          configMap:
            name: mysql-exporter-cnf