apiVersion: v1
kind: Service
metadata:
  name: fastapi-simple-server-service
spec:
  selector:
    app: fastapi-simple-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-simple-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-simple-server
  template:
    metadata:
      labels:
        app: fastapi-simple-server
    spec:
      nodeName: node-0
      containers:
      - name: fastapi-simple-server
        image: sarthak5784/fastapi-simple-server
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m" 
          requests:
            cpu: "500m"
        env:
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: P4ssw0rd
        - name: MYSQL_ROOT_PASSWORD
          value: P@ssw0rd
        - name: MYSQL_DATABASE
          value: fastapi_app
        - name: MYSQL_HOST
          value: mysql
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  ingressClassName: caddy
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi-simple-server-service
            port:
              number: 8000
  tls:
    - secretName: mycerts
      hosts:
        - test.com